name: Implement Certificate from HV - App Services

on:
    repository_dispatch:
      types: [deploy-event]    

jobs:
  automate-certificate:
    uses: gianfra901/demosanddonnuts2024/.github/workflows/certificate.yml@main
    secrets: inherit
    with:
      hv-namespace: ${{ github.event.client_payload.hv-namespace }}
      hv-certificate-path: ${{ github.event.client_payload.hv-certificate-path }}
      az-resource-group-name: ${{ github.event.client_payload.az-resource-group }}
      az-web-app-name: ${{ github.event.client_payload.az-web-app }}
      jira-project-id: ${{ github.event.client_payload.jira-project-id }}
      jira-issue: ${{ github.event.client_payload.jira-issue-id }}